name: OCaml Tasks
on: [ push ]
jobs:
  ci-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v1.1.11
      with:
          ocaml-compiler: 4.14.x
    - name: Install OCaml Dependencies
      run: > 
        opam install . --deps-only --with-test;
        eval $(opam env)
    - name: Compilation Check
      run: make build
    - name: Unit Tests
      run: make test
    - name: ODoc
      run: make doc
