name: OCaml Tasks
on: [ push ]
jobs:
  ci-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v1.1.11
      with:
          ocaml-compiler: 4.14.x
    - name: Run OCaml Tasks
      run: > 
        opam install . --deps-only --with-test;
        eval $(opam env);
        make build;
        make test;
        make doc
    - name: Upload ODoc Artifact
      uses: actions/upload-artifact@v3
      path: _build/default/_doc/_html/index.html
